apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nameserver 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nameserver
subjects:
- kind: ServiceAccount
  name: nameserver 